<?xml version = "1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="tasks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="task" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="description" type="xs:string" minOccurs="0"/>
                            <xs:element name="date" type="xs:string" minOccurs="0"/>
                            <xs:element name="category" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="color" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="task_[0-9]{3}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="importance">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Alta"/>
                                    <xs:enumeration value="Mitjana"/>
                                    <xs:enumeration value="Baixa"/>
                                    <xs:enumeration value="Sense Prioritat"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="is_done">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="false"/>
                                    <xs:enumeration value="true"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
